### ISSUE TITLE
In slate link are not converte correctly

### ISSUE THREAD

**Issue by mcasagrande18** [plone/blocks-conversion-tool#10]
When convert `a` tag for slate blocks type must be `a` not `link`

https://github.com/plone/blocks-conversion-tool/blob/ff9a2523149b0da7484be5a2e2ef7300c9fcc295/src/converters/slate.js#L79

**Comment by ericof** [comment]
@mcasagrande18 This is by design. I had a very long chat with @ichim-david and he explained to me why it should be a `link`
