### ISSUE TITLE
HTML table to slate: First row is always interpreted as header

### ISSUE THREAD

**Issue by mbarde** [plone/blocks-conversion-tool#36]
# What?

When converting a HTML table to slate block the first row is always interpreted as header row (option `hideHeaders` is always `false`).
In my opinion this should only be the case if first `tr` contains `th`-elements.

# Example

Following HTML:

```html
<table>
  <tbody>
    <tr>
      <td>Name:</td>
      <td>Rick</td>
    <tr>
    <tr>
      <td>Address:</td>
      <td>Main Street</td>
    <tr>
  </tbody>
</table>
```

currently results in this:

![Screenshot_2023-09-20_15-14-38](https://github.com/plone/blocks-conversion-tool/assets/4497578/d63442e6-74e9-4c79-8d1e-3145a3531d6d)

(with `hideHeaders: false`)

I think it should be:

![Screenshot_2023-09-20_15-14-19](https://github.com/plone/blocks-conversion-tool/assets/4497578/998407d1-9414-4c75-94d4-55f956ecc2a9)

(with `hideHeaders: true`)

**Comment by davisagli** [comment]
Fixed in `@plone/blocks-conversion-tool` 0.7.1
